### ISSUE TITLE
No module named 'speech_recognition'

### ISSUE THREAD

**Issue by mauroapo** [platelminto/chatgpt-conversation#4]
I run into this problem everytime i try running it 

```
Traceback (most recent call last):
  File "C:\Users\Mauro Araripe\Documents\Projetos\chatgpt-conversation\chatgpt.py", line 4, in <module>
    from record import SpeechRecognizer
  File "C:\Users\Mauro Araripe\Documents\Projetos\chatgpt-conversation\record.py", line 4, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'

```

I tried to pip instal the lib but it couldn't find a version

**Comment by CDunhill** [comment]
I think you need to lose the underscore?
