### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1

### ISSUE THREAD

**Issue by timeuz** [platelminto/chatgpt-conversation#5]
After some seconds with a lot of
```
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
```
I receive this error:

```
Recognized in 22.253703594207764 seconds - maybe try using a small model. See https://github.com/openai/whisper#available-models-and-languages.
Recognized:  You
Traceback (most recent call last):
  File "/home/timeu/PYTHON/chatgpt-conversation/chatgpt.py", line 21, in <module>
    resp = chatbot.get_chat_response(message)
  File "/home/timeu/.local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 54, in get_chat_response
    response = json.loads(response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by Peymankor** [comment]
Same error. Would be nice if someone help us with debugging.
